# Generated by Django 4.1.6 on 2023-02-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_storage", "0002_file_uploaded_at_alter_file_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="file",
            options={
                "ordering": ["-category", "-uploaded_at"],
                "verbose_name": "File",
                "verbose_name_plural": "Files",
            },
        ),
        migrations.AlterField(
            model_name="file",
            name="description",
            field=models.CharField(max_length=128, verbose_name="File description"),
        ),
    ]
